name: skip-bridge
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 2,14 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@main
    with:
      # skip running local tests because they crash on macos-13
      #run-local-tests: false
      #runs-on: "['macos-13', 'macos-14', 'macos-15']"
      # disable export because there are currently problems with shared PCH module cache files with multi-module native export
      run-export: false

