name: skip-bridge
on:
  push:
    branches: [ main ]
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 5 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  call-workflow:
    uses: skiptools/actions/.github/workflows/skip-framework.yml@v1
    with:
      # skip running local tests because they crash on macos-13
      #run-local-tests: false
      runs-on: "['macos-13', 'macos-26', 'ubuntu-24.04']"
      # disable export because there are currently problems with shared PCH module cache files with multi-module native export
      run-export: false
      #run-local-tests: false

