name: skip-bridge
on:
  push:
    branches: '*'
    tags: "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron:  '0 4,14 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  #call-workflow:
    #uses: skiptools/actions/.github/workflows/skip-framework.yml@main

  test-skip-bridge:
    runs-on: macos-13
    steps:
      - uses: gradle/actions/setup-gradle@v4
      - run: brew install skiptools/skip/swift-android-toolchain@6.0
      - uses: actions/checkout@v4
      - run: swift test
